"""empty message

Revision ID: 9cdb1385ad53
Revises: 
Create Date: 2020-09-07 19:36:17.618996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cdb1385ad53'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kategorie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blogeintrag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titel', sa.String(), nullable=False),
    sa.Column('kategorie', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('datum', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['kategorie'], ['kategorie.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blogeintrag')
    op.drop_table('kategorie')
    # ### end Alembic commands ###
